
eureka:
  client:
    register-with-eureka: true     # Register this application as a Eureka client
    fetch-registry: true           # Fetch registry from the Eureka server
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

