server:
  port: 8082  # The port your client app runs on

spring:
  application:
    name: USER-SERVICE   # Unique service name registered in Eureka

  datasource:
    url: jdbc:mysql://localhost:3306/awsuserdb
    username: root
    password: Saibaba9
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true        # <-- FIXED: must be under jpa
    properties:
      hibernate:
      # dialect: org.hibernate.dialect.Oracle21cDialect
      dialect:   org.hibernate.dialect.MySQL8Dialect

  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

