eureka:
  client:
    register-with-eureka: true     # Register this application as a Eureka client
    fetch-registry: true           # Fetch registry from the Eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/awsuserdb
    username: root
    password: Saibaba9
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect:   org.hibernate.dialect.MySQL8Dialect

  cloud:
    compatibility-verifier:
      enabled: false  # Optional: disables Spring Cloud version compatibility check


  instance:
    prefer-ip-address: true        # Register using IP instead of hostname
    instance-id: ${spring.application.name}:${server.port}  # Unique instance ID
